/*CREADO POR: Grupo 2
FECHA: 20/03/2025
PROYECTO FINAL: Avance 02 con el Esquema ABBOTT*/ 

--============================= USUARIOS Y ROLES =============================--

-- Creacion de los 5 usuarios del sistema
CREATE USER Usuario1 IDENTIFIED BY "12345";
CREATE USER Usuario2 IDENTIFIED BY "23451";
CREATE USER Usuario3 IDENTIFIED BY "34512";
CREATE USER Usuario4 IDENTIFIED BY "45123";
CREATE USER Usuario5 IDENTIFIED BY "51234";

ALTER SYSTEM SET common_user_prefix = '' scope = spfile;

-- Creacion de los 3 roles: Administrador, Supervisor, Operador
CREATE ROLE ROL_ADMIN_BD;
CREATE ROLE ROL_SUPERVISOR;
CREATE ROLE ROL_OPERADOR;

-- Asignacion de los roles creados a los usuarios
GRANT ROL_ADMIN_BD TO Usuario1;
GRANT ROL_SUPERVISOR TO Usuario2;
GRANT ROL_OPERADOR TO Usuario3;
GRANT ROL_SUPERVISOR TO Usuario4;
GRANT ROL_OPERADOR TO Usuario5;

--=============================== PRIVILEGIOS ===============================--
-- Asignacion de privilegios ROL ADMINISTRADOR
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO ROL_ADMIN_BD;
GRANT EXECUTE ANY PROCEDURE, SELECT ANY TABLE TO ROL_ADMIN_BD;
GRANT ALL PRIVILEGES TO ROL_ADMIN_BD;

-- Asignaciones de permisos de lectura y escritura (CRUD) en ROL SUPERVISOR y ROL OPERADOR
-- SUPERVISOR
GRANT CREATE SESSION TO ROL_SUPERVISOR;
-- Crud
GRANT SELECT, INSERT, UPDATE, DELETE ON Estado TO ROL_SUPERVISOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Tareas TO ROL_SUPERVISOR;
GRANT SELECT ON Roles TO ROL_SUPERVISOR;
GRANT SELECT ON Areas TO ROL_SUPERVISOR;
GRANT SELECT ON Area_Rol TO ROL_SUPERVISOR;
GRANT SELECT ON Bodegas TO ROL_SUPERVISOR;
GRANT SELECT ON Materiales TO ROL_SUPERVISOR;
GRANT SELECT ON Bodega_Material TO ROL_SUPERVISOR;
GRANT SELECT ON Datos_Entregas TO ROL_SUPERVISOR;
GRANT SELECT ON Entregas TO ROL_SUPERVISOR;
GRANT SELECT ON Horario TO ROL_SUPERVISOR;
GRANT SELECT ON Personal TO ROL_SUPERVISOR;
GRANT SELECT ON Ingresos TO ROL_SUPERVISOR;
GRANT SELECT ON Inventario TO ROL_SUPERVISOR;
GRANT SELECT ON Registro_Diario TO ROL_SUPERVISOR;
GRANT SELECT ON Reportes TO ROL_SUPERVISOR;

-- OPERADOR
GRANT CREATE SESSION TO ROL_OPERADOR;
-- Crud
GRANT SELECT, INSERT, UPDATE, DELETE ON Datos_Entregas TO ROL_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Entregas TO ROL_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Ingresos TO ROL_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Inventario TO ROL_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON Registro_Diario TO ROL_OPERADOR;
GRANT SELECT ON Materiales TO ROL_OPERADOR;
GRANT SELECT ON Bodega_Material TO ROL_OPERADOR;
GRANT SELECT ON Personal TO ROL_OPERADOR; 


/* Verificaciones de los usuarios creados y sus contraseñas
SELECT * FROM DBA_Users 
WHERE USERNAME = 'USUARIO1';

SELECT * FROM DBA_Users 
WHERE USERNAME = 'USUARIO2';

SELECT * FROM DBA_Users 
WHERE USERNAME = 'USUARIO3';

SELECT * FROM DBA_Users 
WHERE USERNAME = 'USUARIO4';

SELECT * FROM DBA_Users 
WHERE USERNAME = 'USUARIO5';
*/



