-- Tabla: FIDE_ESTADO_TB
CREATE SEQUENCE SEQ_FIDE_ESTADO_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_TIPOS_ROL_TB
CREATE SEQUENCE SEQ_FIDE_TIPOROL_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_ROLES_TB
CREATE SEQUENCE SEQ_FIDE_ID_ROL
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_AREAS_TB
CREATE SEQUENCE SEQ_FIDE_AREA_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_BODEGAS_TB
CREATE SEQUENCE SEQ_FIDE_BODEGA_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_MATERIALES_TB
CREATE SEQUENCE SEQ_FIDE_ID_MATERIAL
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_BODEGA_MATERIAL_TB
CREATE SEQUENCE SEQ_FIDE_BODEGA_MATERIAL_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_DATOS_ENTREGAS_TB
CREATE SEQUENCE SEQ_FIDE_DATO_ENTREGA_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_ENTREGAS_TB
CREATE SEQUENCE SEQ_FIDE_ID_ENTREGA
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_HORARIO_TB
CREATE SEQUENCE SEQ_FIDE_HORARIO_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_USUARIOS_TB
CREATE SEQUENCE SEQ_FIDE_ID_USUARIO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_EMPLEADOS_TB
CREATE SEQUENCE SEQ_FIDE_UPI
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_PERSONAL_TB
CREATE SEQUENCE SEQ_FIDE_ID_PERSONAL
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_TAREAS_TB
CREATE SEQUENCE SEQ_FIDE_ID_TAREA
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_INGRESOS_TB
CREATE SEQUENCE SEQ_FIDE_ID_INGRESO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_INVENTARIO_TB
CREATE SEQUENCE SEQ_FIDE_ID_INVENTARIO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_REGISTRO_DIARIO_TB
CREATE SEQUENCE SEQ_FIDE_ID_REGISTRO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tabla: FIDE_REPORTES_TB
CREATE SEQUENCE SEQ_FIDE_ID_REPORTE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;



