/*CREADO POR: Grupo 2
FECHA: 20/03/2025
PROYECTO FINAL: Avance 02 con el Esquema ABBOTT*/ 

--============================= USUARIOS Y ROLES =============================--

-- Creacion de los 5 usuarios del sistema
CREATE USER Usuario1 IDENTIFIED BY "12345";
CREATE USER Usuario2 IDENTIFIED BY "23451";
CREATE USER Usuario3 IDENTIFIED BY "34512";
CREATE USER Usuario4 IDENTIFIED BY "45123";
CREATE USER Usuario5 IDENTIFIED BY "51234";

ALTER SYSTEM SET common_user_prefix = '' scope = spfile;

-- Creacion de los 3 roles: Administrador, Supervisor, Operador
CREATE ROLE ROL_ADMIN_BD;
CREATE ROLE ROL_SUPERVISOR;
CREATE ROLE ROL_OPERADOR;

-- Asignacion de los roles creados a los usuarios
GRANT ROL_ADMIN_BD TO Usuario1;
GRANT ROL_SUPERVISOR TO Usuario2;
GRANT ROL_OPERADOR TO Usuario3;
GRANT ROL_SUPERVISOR TO Usuario4;
GRANT ROL_OPERADOR TO Usuario5;

--=============================== PRIVILEGIOS ===============================--
-- Asignacion de privilegios ROL ADMINISTRADOR
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO ROL_ADMIN_BD;
GRANT EXECUTE ANY PROCEDURE, SELECT ANY TABLE TO ROL_ADMIN_BD;
GRANT ALL PRIVILEGES TO ROL_ADMIN_BD;

-- Asignaciones de permisos de lectura y escritura (CRUD) en ROL SUPERVISOR y ROL OPERADOR
-- SUPERVISOR
GRANT CREATE SESSION TO ROL_SUPERVISOR;
-- Crud
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_Estado_TB TO ROL_SUPERVISOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_Tareas_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Roles_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Areas_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Area_Rol_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Bodegas_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Materiales_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Bodega_Material_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Datos_Entregas_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Entregas_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Horario_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Personal_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Ingresos_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Inventario_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Registro_Diario_TB TO ROL_SUPERVISOR;
GRANT SELECT ON FIDE_Reportes_TB TO ROL_SUPERVISOR;


-- OPERADOR
GRANT CREATE SESSION TO ROL_OPERADOR;
-- Crud
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_Datos_Entregas_TB TO ROL_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_Entregas_TB TO ROL_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_Ingresos_TB TO ROL_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_Inventario_TB TO ROL_OPERADOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON FIDE_Registro_Diario_TB TO ROL_OPERADOR;
GRANT SELECT ON FIDE_Materiales_TB TO ROL_OPERADOR;
GRANT SELECT ON FIDE_Bodega_Material_TB TO ROL_OPERADOR;
GRANT SELECT ON FIDE_Personal_TB TO ROL_OPERADOR; 




