--Este trigger verifica si el ID_USUARIO viene como NULL, y si es así, asigna automáticamente el siguiente valor de la secuencia.

CREATE SEQUENCE FIDE_USUARIOS_TB_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER FIDE_USUARIOS_TB_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    SELECT FIDE_USUARIOS_TB_SEQ.NEXTVAL
    INTO :NEW.ID_USUARIO
    FROM dual;
  END IF;
END;
/


--mantener el control automático de IDs de materiales
CREATE SEQUENCE FIDE_MATERIALES_TB_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER FIDE_MATERIALES_TB_TRG
BEFORE INSERT ON FIDE_MATERIALES_TB
FOR EACH ROW
BEGIN
  IF :NEW.ID_MATERIAL IS NULL THEN
    SELECT FIDE_MATERIALES_TB_SEQ.NEXTVAL
    INTO :NEW.ID_MATERIAL
    FROM dual;
  END IF;
END;
/


--asigna automáticamente un HORARIO_ID usando la secuencia cuando se inserta un nuevo horario y no se proporciona uno.

CREATE SEQUENCE FIDE_HORARIO_TB_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER FIDE_HORARIO_TB_TRG
BEFORE INSERT ON FIDE_HORARIO_TB
FOR EACH ROW
BEGIN
  IF :NEW.HORARIO_ID IS NULL THEN
    SELECT FIDE_HORARIO_TB_SEQ.NEXTVAL
    INTO :NEW.HORARIO_ID
    FROM dual;
  END IF;
END;
/

--asigna automáticamente un ESTADO_ID mediante la secuencia cuando se inserta un nuevo estado sin especificar el ID

CREATE SEQUENCE FIDE_ESTADO_TB_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
  IF :NEW.ESTADO_ID IS NULL THEN
    :NEW.ESTADO_ID := FIDE_ESTADO_TB_SEQ.NEXTVAL;
  END IF;
END;
/


--asigna automáticamente un HORARIO_ID usando una secuencia cuando no se especifica manualmente.


CREATE SEQUENCE FIDE_HORARIO_TB_ALT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE OR REPLACE TRIGGER FIDE_HORARIO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_HORARIO_TB
FOR EACH ROW
BEGIN
  IF :NEW.HORARIO_ID IS NULL THEN
    :NEW.HORARIO_ID := FIDE_HORARIO_TB_ALT_SEQ.NEXTVAL;
  END IF;
END;
/


--genera automáticamente el DATO_ENTREGA_ID antes de cada inserción usando la secuencia FIDE_DATOS_ENTREGAS_TB_SEQ

CREATE SEQUENCE FIDE_DATOS_ENTREGAS_TB_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE OR REPLACE TRIGGER FIDE_DATOS_ENTREGAS_TB_TRG
BEFORE INSERT ON FIDE_DATOS_ENTREGAS_TB
FOR EACH ROW
BEGIN
  IF :NEW.DATO_ENTREGA_ID IS NULL THEN
    :NEW.DATO_ENTREGA_ID := FIDE_DATOS_ENTREGAS_TB_SEQ.NEXTVAL;
  END IF;
END;
/


--asignar automáticamente el ID_MATERIAL al insertar un nuevo material, utilizando la secuencia FIDE_MATERIALES_TB_SEQ

CREATE SEQUENCE FIDE_MATERIALES_TB_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE OR REPLACE TRIGGER FIDE_MATERIALES_TB_ID_TRG
BEFORE INSERT ON FIDE_MATERIALES_TB
FOR EACH ROW
BEGIN
  IF :NEW.ID_MATERIAL IS NULL THEN
    :NEW.ID_MATERIAL := FIDE_MATERIALES_TB_ID_SEQ.NEXTVAL;
  END IF;
END;
/


--asegura que cada vez que se inserte un nuevo estado, se genere automáticamente un ESTADO_ID mediante la secuencia FIDE_ESTADO_TB_ID_SEQ

CREATE SEQUENCE FIDE_ESTADO_TB_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_ID_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
  IF :NEW.ESTADO_ID IS NULL THEN
    :NEW.ESTADO_ID := FIDE_ESTADO_TB_ID_SEQ.NEXTVAL;
  END IF;
END;
/

--asegura que cada vez que se inserte un nuevo rol, se genere automáticamente un ID_ROL mediante la secuencia FIDE_ROLES_TB_ID_SEQ


CREATE SEQUENCE FIDE_ROLES_TB_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE OR REPLACE TRIGGER FIDE_ROLES_TB_ID_TRG
BEFORE INSERT ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
  IF :NEW.ID_ROL IS NULL THEN
    :NEW.ID_ROL := FIDE_ROLES_TB_ID_SEQ.NEXTVAL;
  END IF;
END;
/


--se encarga de generar automáticamente un ESTADO_ID mediante la secuencia FIDE_ESTADO_TB_ID_SEQ cuando se inserta un nuevo estado en la tabla FIDE_ESTADO_TB

CREATE SEQUENCE FIDE_ESTADO_TB_SEQ_NEW
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE OR REPLACE TRIGGER FIDE_ESTADO_TB_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
  IF :NEW.ESTADO_ID IS NULL THEN
    :NEW.ESTADO_ID := FIDE_ESTADO_TB_SEQ_NEW.NEXTVAL;
  END IF;
END;
/












